x-common: &common
  working_dir: /app
  volumes:
    - ./:/app
  user: 1000:1000

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  backend:
    <<: *common
    depends_on:
      - postgres
    image: oven/bun:1-alpine
    entrypoint: [bun, --cwd, backend, dev]
    ports:
      - 3000:3000

  frontend:
    <<: *common
    depends_on:
      - backend
    image: imbios/bun-node:22-alpine
    entrypoint: [bun, --cwd, frontend, dev, --host, 0.0.0.0]
    ports:
      - 5173:5173

volumes:
  postgres:
