x-compose-file: &compose-file packages/create-app/template/compose.yaml

x-overrides: &overrides
  working_dir: /app/packages/create-app/template
  volumes:
    - ${PWD}:/app

services:
  postgres:
    extends:
      file: *compose-file
      service: postgres

  init_db:
    extends:
      file: *compose-file
      service: init_db
    <<: *overrides

  backend:
    extends:
      file: *compose-file
      service: backend
    <<: *overrides
  frontend:
    extends:
      file: *compose-file
      service: frontend
    <<: *overrides

volumes:
  postgres:
