name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.43

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-dependencies-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
          path: node_modules

      - name: Cache lint results
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-lint-${{ hashFiles('bun.lock', 'eslint.config.ts', 'stylelint.config.ts') }}
          path: |
            .eslintcache
            .stylelintcache

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Lint
        run: bun run check:eslint --cache-strategy content && bun run check:stylelint --cache-strategy content

      - name: Type check
        run: bun run check:types
