name: 🚀 New feature proposal
description: Propose a new feature to be added to Cloudstack
title: 'feat: '
labels: [✨ enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to file a feature request. Please fill out this form as completely as possible.
  - type: textarea
    attributes:
      label: Describe the feature you'd like to request
      description: Please describe the feature as clear and concise as possible. Remember to add context as to why you believe this feature is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the solution you'd like to see
      description: Please describe the solution you would like to see. Adding example usage is a good way to provide context.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe alternate solutions
      description: |
        Please describe alternate solutions you have considered. What makes your suggested feature better?
        If you currently have a workaround to get a similar experience, add that here.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional information
      description: Add any other information related to the feature here. If your feature request is related to any issues or discussions, link them here.
  - type: checkboxes
    attributes:
      label: Validations
      description: Before submitting the feature request, please make sure you do the following
      options:
        - label: Read the [Contributing Guidelines](https://github.com/kevinmarrec/cloudstack/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't [already an issue](https://github.com/kevinmarrec/cloudstack/issues) that requests the same feature to avoid creating a duplicate.
  - type: checkboxes
    attributes:
      label: 👨‍👧‍👦 Contributing
      description: We love contributors in any shape or form. Would you be willing to implement this feature?
      options:
        - label: 🙋‍♂️ Yes, I'd be down to file a PR implementing this feature!
