name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      ${{ !startsWith(github.event.head_commit.message, 'chore: release') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo commit message
        run: echo "${{ github.event.head_commit.message }}"
