name: Continuous Integration

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: read

jobs:
  changes:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      workspaces: ${{ steps.filter.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Cache dependencies & packages dist
        uses: actions/cache/save@v4
        with:
          path: |
            **/node_modules/**
            **/dist/**
          key: ${{ github.sha }}

      - name: Filter paths
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            packages/eslint-config:
              - '.github/workflows/ci.yml'
              - 'packages/eslint-config/**'
            packages/stylelint-config:
              - '.github/workflows/ci.yml'
              - 'packages/stylelint-config/**'
            packages/unocss-config:
              - '.github/workflows/ci.yml'
              - 'packages/unocss-config/**'
            packages/frontend:
              - '.github/workflows/ci.yml'
              - 'packages/frontend/**'
  test:
    name: Test
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.workspaces != '[]' }}
    strategy:
      matrix:
        workspace: ${{ fromJSON(needs.changes.outputs.workspaces) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Restore cached dependencies & packages dist
        uses: actions/cache/restore@v4
        with:
          path: |
            **/node_modules/**
            **/dist/**
          key: ${{ github.sha }}

      - name: Check unused files, dependencies, and exports
        run: bun knip -W ${{ matrix.workspace }}

      - name: Run Lint
        run: bun --cwd ${{ matrix.workspace }} lint

      - name: Run Tests
        run: bun --cwd ${{ matrix.workspace }} test --run
