name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: package.json

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: package.json

      - name: Cache lint results
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-lint-${{ hashFiles('bun.lock', 'eslint.config.ts', 'packages/eslint-config/src/index.ts', 'stylelint.config.ts', 'packages/stylelint-config/src/index.ts') }}
          path: |
            .eslintcache
            .stylelintcache

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check unused files, dependencies, and exports
        run: bun run check:unused

      - name: Lint
        run: bun run check:eslint --cache-strategy content && bun run check:stylelint --cache-strategy content

      - name: Type check
        run: bun run check:types

      - name: Unit tests
        run: bun run test --coverage
