name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-and-test:
    name: Check & Test
    runs-on: ubuntu-latest
    if: |
      !startsWith(github.event.head_commit.message, 'chore: release')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.42

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-dependencies-${{ hashFiles('bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-
          path: node_modules

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: bun install --frozen-lockfile

      - name: Run postinstall script
        if: steps.cache.outputs.cache-hit == 'true'
        run: bun run postinstall

      - name: Check unused files, dependencies, and exports
        run: bun run knip

      - name: Lint
        run: bun run lint

      - name: Type check
        run: bun run typecheck

      - name: Unit tests
        run: bun run test --coverage
