name: Dependencies updates

on:
  workflow_dispatch: {}

jobs:
  check:
    name: List latest versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1

      - name: Run Taze
        run: bunx taze major -r
